### ISSUE TITLE
Support for pushing mu-plugins

### ISSUE THREAD

**Issue by andyinabox** [welaika/wordmove#117]
It's pretty clear from #116 that there is no support for pushing plugins in the `mu-plugins` directory, but I'm curious why. Is this a "no time for frivolities" omission or a principled stance against use of the `mu-plugins` directory? It seems like it wouldn't be all that difficult to implement.

**Comment by pioneerskies** [comment]
Hi @andyinabox and thanks for your interest. `mu-plugins` is not a problem per se; is overall the WP MU support: moving a single wordpress install is not the same work as moving a MU install.

So implementing just the support for `mu-plugins` wouldn't be enough to support the whole MU thing.

Decision was about -all or nothing- and nothing won, because we don't work on MU installations actually. But please, consider the openness of the code and how welcome contributions are. We will be really happy to support and review a pull request in the MU direction.

What do you think about this topic?

**Comment by andyinabox** [comment]
Ah yes ok — I think I was not seeing the use of the `mu-plugins` in the larger context, as I'm newer to WordPress. I have been using it simply as a way of including "required" plugins in a site infrastructure outside of the built-in plugin architecture. It's clear now after doing a bit of research that there's a larger history tied to the WP multisite setup (which I haven't yet worked with).

**Comment by alisspers** [comment]
Hi guys,
@pioneerskies : I think there might be a confusion here about mu-plugins. It is true that initially they came from WordPress MU (called Multisite ever since they merged it into core), but nowadays they have nothing to do with Multisite. The name actually translates to Must use-plugins (more info here: http://codex.wordpress.org/Must_Use_Plugins).

That being said, I'd just like to add my vote for this feature. I think it would be a great addition.

**Comment by pioneerskies** [comment]
@andyinabox @alisspers you're both right: this is really just a matter of misunderstanding! :P

I'm tagging this as a feature request and, yes, that shouldn't be hard stuff to implement :)

As always anyone feel free to open a pull request

**Comment by josephbergdoll** [comment]
+1

**Comment by torounit** [comment]
+1

**Comment by pioneerskies** [comment]
@delphaber due to the popularity of this feature we should consider to insert it in the next milestone and eventually "snooze" the due date. We could talk about this the next Friday.

**Comment by endorama** [comment]
@pioneerskies @delphaber count me in if you need some help implementing this feature! :)

**Comment by pioneerskies** [comment]
We're on the way to check this PR https://github.com/welaika/wordmove/pull/206 about this feature

**Comment by pioneerskies** [comment]
@andyinabox @torounit @josephbergdoll this is shipped in current pre-release gem.
Please refer to #206
