### ISSUE TITLE
SFTP Support

### ISSUE THREAD

**Issue by regs79** [welaika/wordmove#133]
Is there anyway to enable SFTP with wordmove? 

I can't see any configuration option for it, but it seems like there should be one as photocopier has support.

**Comment by endorama** [comment]
Hi! Currently no ( @delphaber correct me if I'm wrong ).

Wordmove uses [Photocopier](https://github.com/welaika/photocopier) gem at version 0.0.10, which does not support SFTP.

There is already an issue https://github.com/welaika/photocopier/issues/14 for SFTP support, has been implemented and Photocopier has been updated to `1.0.0-pre` for testing. I didn't had time to test this myself, so is still pending.

If you'd like to test Wordmove with the new Photocopier you can report results on the Photocopier repository, so that gem is promoted to stable and Wordmove dependency is updated!

**Comment by regs79** [comment]
Hi!

Thanks for the response. I'm not much of a Ruby guy but I think I've worked it out.

I installed the `1.0.0-pre` initially but couldn't get wordmove to talk to it although I changed all references to the version.

What I ended up doing was going to looking at the changes in the last [commit] (https://github.com/welaika/photocopier/commit/38bb458b72bb494ce9378d08678fe72def7b95a1) and added them manually to the `0.0.10` version of photocopier and it worked.

That's probably not enough for you to update, but I appreciate the advice. :+1:

**Comment by delphaber** [comment]
Thank you @endorama @regs79  :)

Next release of wordmove will use photocoper 1.0

**Comment by gwelser** [comment]
Any word on upgrading to Photocopier 1.0 so we can enable SFTP?

**Comment by pioneerskies** [comment]
Sorry for the long waiting, but we are still waiting to schedule Wordmove's pre-release using the updates Photocopier...really sorry...
I'll try to force a bit the schedule w/ my colleagues.

**Comment by pioneerskies** [comment]
We're not on the way of a new release, but very close to a pre-release (installable via `gem install wordmove --pre`) in order to start to test it the easy way.

**Comment by joeguilmette** [comment]
That would be awesome!

**Comment by pioneerskies** [comment]
@regs79 @gwelser @joeguilmette you could be interested in this: https://github.com/welaika/wordmove/issues/174#issuecomment-118370169

Enjoy testing :)

**Comment by onlyskyguy** [comment]
Is SFTP support still on schedule for next release?
