### ISSUE TITLE
Using wordmove with Desktop Server

### ISSUE THREAD

**Issue by kinnedev** [welaika/wordmove#143]
I am getting an error when trying to push all to remote server. 

mysqldump: command not found

I am using Desktop Server as my local environment. 

Thank You

**Comment by pioneerskies** [comment]
Personally I have no idea what Desktop Server is, I'm sorry.
Anyway `mysqldump` is a standard command shipped w/ the MySQL installation; in order to let Wordmove use that executable you must have it inside your $PATH and be able to launch it right from your command line.

You can discover if it is in your $PATH using `which mysqldump` command; if nothing is returned than you're experiencing environment problems.

Hope you'll have some clues from this. Reopen the issue if you need to iterate on it. :)

**Comment by squaremunkey** [comment]
Found a solution to the problem just add this to your terminal before wordove push

export PATH=$PATH:/Applications/XAMPP/xamppfiles/bin
