### ISSUE TITLE
Pull selected theme

### ISSUE THREAD

**Issue by oterox** [welaika/wordmove#156]
Hi,

is it possible to get just one theme, something like:
wordmove pull -e staging -t "selectedtheme"

Instead of getting all themes?

This would be very useful as we can have some themes but be working only on one of them.

**Comment by joeguilmette** [comment]
What would be the benefit of this? To save time on the download?

**Comment by oterox** [comment]
yes, lets say you have 10 themes, why to download all if you're only
working on 1
The same for plugins. Some clients have 20+ plugins, why to download/upload
all if you just need one?

Speed is important too.Lets say i'm working on the airport or the hotel,
the speed would probably be really bad.

Its similar to working with databases.You always have commands to apply to
one table, not all tables ;)

I think it would be a nice feature

Best.

**Comment by pioneerskies** [comment]
Hi there!

You're ideas is obviously nice; let me enumerate some points anyway:

1. If you have 10 themes you delete (or advice to delete) 9 of them, from my point of view. First of all from a security perspective.
2. choose a single theme or a single plugin will bring us to support multiple plugins/themes also. We should consider to implement widest possible approaches in order to satisfy a wider range of users and situations.
3. Isn't `rsync-options` a good choice - even if a bit advanced regard of skills requirements - in order to customize what you are push/pulling?
4. Rsync will always transfer just the modified files. Also LFTP tries to do the same thing...but, well I hate FTP and discourage everybody to use it whenever possible :)
5. Rsync doesn't support exclude regexes...really a pity :(
6. In the meanwhile we can manually exclude themes and plugins (a pain in the neck, but just once a time per project)

That said, I'll tag as feature your issue, in the hope some else will iterate over it and hopefully drop some ideas.

Really really thanks for sharing your thoughts and needs w/ all of us

**Comment by oterox** [comment]
hey,

3) Absolutely!!! it probably would be awesome if you could add some samples
to the documentation to use "rsync-options"

I'm using rsync alone and works nice but now that i've discovered Wordmove
i LOVE it :)

**Comment by pioneerskies** [comment]
Glad to hear that. As per the readme:

```
# ssh:
  #   host: "host"
  #   user: "user"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.
```

The problem at the moment is that the underlying `photocopier` gem was unable to handle multiple arguments, as per the issue. I'll ask @delphaber about the release status of the last version of `photocopier`, which will support an array as argument:

```
rsync_options: [ "--bwlimit=256", "--human-readable", "--partial" --exlcude="wp-content/themes", --inlcude="wp-content/themes/mycooltheme"]
```

That way we **should** be able to customize rsync just as using it directly from the cli.

And yes, if the feature is ready and released, we'll have to update the readme :)

**Comment by mukkoo** [comment]
@delphaber @pioneerskies some news about this?

**Comment by pioneerskies** [comment]
Just reviewed the issue and...it could be solved.

1. We support multiple rsync options; not with the notation of my previous post but simply separating them by spaces

2. themes should be excluded in the `Movefile`'s `exlcude` section of the concernign stage such like

```yaml
  exclude:
  - wp-content/themes/badtheme
  - wp-content/themes/idonotwantyoutheme
  - [...]
```
