### ISSUE TITLE
Gateway params in Movefile

### ISSUE THREAD

**Issue by jmsilcom** [welaika/wordmove#175]
hi there. 
Can u tell me more about "gateway" under SSH part in Movefile?
What is the utility of this option ?

Thanks in advance.

**Comment by pioneerskies** [comment]
Hello!

Those options (implemented at the begigging of the time I think :) ) are an interface against another gem: https://github.com/net-ssh/net-ssh-gateway which is a Wordmove's dependency.

I suppose is intended to connect into a bastion server through SSH (the gateway) and then to the final server (probably inside a private network.

DevMachine----------ssh------>GATEWAY----------ssh--------->REMOTE ENVIRONEMENT (here we'll do the deploy)

I'll ask if any colleague knows more about it, since personally never used (I have ProxyCommand ssh's config on my laptop when needed)

Cheers!
