### ISSUE TITLE
Your logo is missing the 'D'

### ISSUE THREAD

**Issue by Chrisedmo** [welaika/wordmove#197]
I noticed there is a new logo in your README.md - however It is missing the 'd' so it reads Wormove. If you let me know the font I could fix it for you?

**Comment by delphaber** [comment]
Fail..... :D Thank you very much :) We are going to fix it soon ;)

**Comment by Arkham** [comment]
HAHAHAHA

**Comment by jirsbek** [comment]
+1 :laughing:

**Comment by mukkoo** [comment]
Fixed. Tank you.

**Comment by wpbullet** [comment]
I plan to make some tutorials for Wordmove and would love to get an svg version of the logo if possible. I can make my own if you can share which font it is, thanks.

**Comment by pioneerskies** [comment]
Hey @wpbullet , I'm going to ping my colleague @mukkoo in order to put the SVG version inside the repository. He will give you a ping back when done :)

Thanks for your interest in Wordmove; we will be pleased to link your tutorials in the readme and/or in the wiki when they will be published, so feel free to contact us (mention me in the slack channel and i will be up and running asap)

**Comment by mukkoo** [comment]
Hi @wpbullet. The font is "Pacifico" and you can download it here: https://www.fontsquirrel.com/fonts/pacifico 

Attached the logo SVG.
[Wordmove_Logo.svg.zip](https://github.com/welaika/wordmove/files/693889/Wordmove_Logo.svg.zip)

**Comment by wpbullet** [comment]
Thank you @mukkoo and @pioneerskies . I will be sure to update you when I have some tutorials up :)
