### ISSUE TITLE
Request: Color the progress to see what's failing

### ISSUE THREAD

**Issue by iDuuck** [welaika/wordmove#198]

**Comment by pioneerskies** [comment]
Hi @iDuuck ,

thanks for your proposal; have you got some examples (snipet, screenshots) about the problem and an example of how you'd like to change it?
Overall is not an easy task to format the output, because Wordmove works on remote environments, so  is not always that easy to grab remote errors. Even more when using FTP as transfer protocol.

If you'll elaborate a bit on the idea we'll take a little investigation

**Comment by iDuuck** [comment]
Normally the ftp client (in this case written in ruby) is getting the output of the remote console and then it's possible to color some things from the string, isn't it?
