### ISSUE TITLE
Error with final phase of DB Move 

### ISSUE THREAD

**Issue by wbuist** [welaika/wordmove#300]
local | adapt dump
/Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/sql_adapter.rb:44:in `gsub!': invalid byte sequence in UTF-8 (ArgumentError)

Any ideas on what I need to do to fix this?

**Comment by wbuist** [comment]
Interestingly if i run the dump.sql with phpmyadmin it runs happily. The website though won't load on chrome (no data returned) but loads fine on safari. 

That's odd too.

**Comment by wbuist** [comment]
Tried going the other way (push to staging) and still get this error 

local | adapt dump
/Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/sql_adapter.rb:44:in `gsub!': invalid byte sequence in UTF-8 (ArgumentError)

Any ideas?

**Comment by pioneerskies** [comment]
The help about these issues is in the wiki: https://github.com/welaika/wordmove/wiki/invalid-byte-sequence-in-UTF-8-while-pushing---pulling-db

With the baleful advent of utf8-mb4 those problems are arising everywhere for everyone who is using staging/production environments with mysql versions prior to 5.5.3; and the only `Wordmove`'s fault - imho - is that it not trying to alter your encoding/collation automagically because it could leads to loss/degradation of some data.

Closing this one. Follow-ups are always welcome
