### ISSUE TITLE
Replace multiple URLs

### ISSUE THREAD

**Issue by dezinerdudes** [welaika/wordmove#316]
Say if I am moving a wp site with a db that contains different forms of the same URL, how would you specify the alternative URLs for wordmove to replace? Could one specify extra vhosts?

For instance, if I wanted to move a site https://www.example.com, Wordmove will by default not replace occurances of http://www.example.com or just www.example.com. Alternatives such as WP Migrate DB Pro allow you to specify additional URLs to replace. And unfortunately at the moment I have a site with exactly that problem, and I really prefer to use Wordmove. What could I do? @pioneerskies please any advice would be much appreciated.

**Comment by pioneerskies** [comment]
Oh well,

the short answer is: no, we can't do that.

The long one: we can't because Wordmove is not a general purpose search and replace tool. It aim to replace the domain in order to keep the database working when moved on a different one. It would be technically affordable to introduce as a feature, but there are other brilliant solution out there to replace arbitrary strings. My favorite one is *wp-cli* with no doubt.

We use wp-cli to do a lot of things in our wp workflow and possibly in the future we will make wordmove working aside of wp-cli as we have done with another gem (Wordless gem). E.g.: I'd write a little deploy script

> deploy_db.sh

```bash
#!/usr/bin/env bash

wp search-replace 'www.example.com' 'www.mydomain.com' wp_posts
wordmove push -d -e stanging
```

I'd save it in my project's root and in my GiT repo and I'd use it as a wrapper for my deploy utilities.

If you don't know wp-cli, [go and start using it](http://wp-cli.org/commands/search-replace/) because it's a developer must have IMHO.

That said: if you think this should be a feature inside Wordmove we can label the issue as a feature request. But I don't think we will develop features until the next fall. PR are obviously always welcome.

Hope you'll find inspirations :)

**Comment by dezinerdudes** [comment]
Thanks @pioneerskies, really appreciate the info. Also thanks for the tip of using wp-cli to replace DB strings, will definitely give that a try! Thanks again
