### ISSUE TITLE
Running with Vagrant

### ISSUE THREAD

**Issue by dsgnr** [welaika/wordmove#317]
I am moving over to Vagrant from Mamp Pro. I have successfully managed to install WordMove on my vagrant box but I'm having issues with SSH keys from inside vagrant. 

Instead of me having to log into vagrant ssh to run Wordmove, can I still run Wordmove from my local machine like I could with Mamp? I remember reading somewhere about having to login to ssh to run Wordmove but just seems a bit long winded having to log in then log out constantly. 

I imagine files should be okay but I suspect the Db may cause issues?

I am hoping to try tomorrow but thought I'd ask before spending hours on something that isn't possible!

Thanks

**Comment by endorama** [comment]
I suggest you to look at vagrant-exec (
https://github.com/p0deje/vagrant-exec ) and ssh agent forwarding ( nice
documentation from github
https://developer.github.com/guides/using-ssh-agent-forwarding/ )

Basically instead of running wordmove from you local machine you run
everything inside vagrant, without the burden of logging in every time.

vagrant-exec is a vagrant plugin that permits to execute command inside
vagrant from the host machine; it also gives you the possibility to create
'binstubs' for your program: you run a specific file created by
vagrant-exec that is a proxy to the same command inside the vagrant
machine. It is really handy!

The ssh agent forwarding let's you use your host ssh keys instead of the
keys in the vagrant machine. This way you can log in to remote server as
the host user and not the vagrant user.

This way everything is contained inside vagrant ( both WordPress and
development tools ) but you can execute all commands as you were on your
local machine.

**Comment by pioneerskies** [comment]
@endorama <3
