### ISSUE TITLE
Rsync permissions error - solved but unhappy. Please help?

### ISSUE THREAD

**Issue by dsgnr** [welaika/wordmove#322]
Hey,

I've recently been setting up a new Digital Ocean droplet. It seems that when the permissions were correct for Wordmove to successfully rsync up or down, WordPress would not have enough permissions to update/install themes etc. Then if I change the users permissions, rsync would work, but not WordPress.

With a help of a friend, we have managed to get it to work correctly but it meant having to change the user of both nginx and php to my user (the same as in wordmove file, instead of www-data.) Despite the user being inside the www-data group with adequate permissions.

Although it works, I'm not 100% happy with having nginx and php as a different user instead of www-data.

Any thoughts on this at all?

Thanks!

**Comment by pioneerskies** [comment]
Hi @dsgnr , and sorry if we get here always late these times.

I absolutely have a *really* opinionated approach to your un-happiness. I hope you'll not consider me rude 👅 

The spot here, IMHO, is that we are not sysadmin, and VPS will not run well and securely without a sysadmin.

Let's consider your case: it's obvious that if you have a user in the www-data group:

1. www-data has to be the primary group
2. your user must have the right umask in order to write files actually readable from other users of the same group
3. most of the time you should be aware of what a `setgid` flag is in order to manage such situations

Moreover you shouldn't have the web-server running as another user, but is your user who should write files with the right group.

In hosted these behaviours are setup by default and you have not to worry about nothing. If you manage a VPS on your own, you should be familiar with these problems.

Probably solutions like serverpilot.io could be valid alternatives.

So, my answer, and please: take it a joke, is **that's unix, brah**

Plase, take also in consideration the capability of `rsync` to actually write files with programmatic permissions if the calling user has capability to do it. And `wordmove` supports to pass options to the `rsync` command through the `Movefile`. In the wiki and/or in older issues you should find some documentation about this `rsync`'s uber-cool feature.

Cheers
