### ISSUE TITLE
SSH Amazon AWS

### ISSUE THREAD

**Issue by kitecom** [welaika/wordmove#358]
I know there have been a few issues raised and resolved around ssh ids, I'm trying to use wordmove between local and an AWS EC2 instance. 
Pulling files/directories gives me:
Permission denied (publickey)
Pulling database gives me:  Authentication failed for user [username@aws-url] (Net::SSH::AuthenticationFailed).

Is there a line of config that would allow me to point wordmove at my PPK, or even better, import a Putty session?

**Comment by pioneerskies** [comment]
I don't know anything about Putty and Pageant and how they should work on Ubuntu4Windows - are you using U4W? -, but i know how ssh works in *nix...and well, it's pretty much easier :D

I've found this nice article for convertink the Putty Key in a standard ssh key. That done, I'd advice you to configure your connection to the server using `~/.ssh/config` file. Wordmove has not specific options because of the existence of that very sweet ssh configuration file which enables you to do something like

```bash
Host awsserver
  HostName example.com
  User amazonuser
  IdentityFile ~/.ssh/awswpkey
```

and then in your `Movefile`'s `ssh` section simply

```yaml
ssh:
    host: "awsserver"
```

and boom... that's just sweet. I hope you can reproduce it on your OS.
