### ISSUE TITLE
[Documentation] Backups

### ISSUE THREAD

**Issue by strarsis** [welaika/wordmove#403]
I also want to use wordmove for taking backups of database and files (uploads/ folder).
An example in documentation would be a really great addition (or for me a link to it, I haven't found it).

**Comment by pioneerskies** [comment]
Hello there,

I do not get the actual point, sorry :) Wordmove is intended to mirror wordpress installations: backup (remotely) and versioning (locally) are, from my point of view, really different tasks.

Because WP database can't be versioned, Wordmove takes a backup of the remote database before `push`ing and of the local database before `pull`ing. This is the only backup strategy.

What would you like to accomplish further?

**Comment by strarsis** [comment]
@pioneerskies: Thanks for the great explanation. Are there any good tools that work like wordmove (CLI, simple+efficient, using SSH/SFTP) for backing up in regular intervals? 😄

**Comment by pioneerskies** [comment]
Well...that's not an easy question...backing up is a hard matter; I use rdiff-backup for that sort of tasks and I use cron to collect gzipped sql dumps in a directory which is moreover backed up by rdiff.

Obviously this is not a wordpress dedicated approach, but a general one
