### ISSUE TITLE
Everytime it pulls all files in "Uploads" folder

### ISSUE THREAD

**Issue by ryo-k-nd** [welaika/wordmove#497]
When I try pulling the files like this,
`wordmove pull -u -e production`

Every time it pulls all files in "Uploads" folder although it says "receiving incremental file list" without any errors.

In other directories (themes, plugin), there is no problem at all when I try to pull/push from my local.

Does anyone know the reason why?

**Comment by pioneerskies** [comment]
Hello @ryo-k-nd :)

At a first glance I'd bet it could be due to time/permission differences between the two environments. If you'd pass `--itemize-changes` as an `rsync_options`'s parameter you should be able to catch why `rsync` decided to move those files.

In our wiki you can find doc about `rsync_options` while `--itemize-changes` is an `rsync`'s flag so I'd ask you to deepen it in its documentation :)

Let me say if you need help reading the new `rsync`'s output

**Comment by ryo-k-nd** [comment]
@pioneerskies Thank you for your comment.

I have just tried `--itemize-changes` and then all the files show "f+++++++++" in the head.
I have no idea why it happens only in uploads.

**Comment by pioneerskies** [comment]
Have to close this one. Also re-reading the discussion, I've no other cards to play and no one else replied. Sorry

**Comment by chrilleferna** [comment]
I can reply that I had the same issue, and found that it was indeed due to the time difference between my local environament in France and the production server in the UK. I added a modify-window option to rsync like this:
`    rsync_options: "-L --verbose --modify-window=3610" # Additional rsync options, optional
`
and now things work as they should.
