### ISSUE TITLE
`block in push_exclude_paths': undefined method `match?' for "wp-content":String (NoMethodError)

### ISSUE THREAD

**Issue by CaptainPirateFace** [welaika/wordmove#538]
When pushing -u -t -p -l  --all etc, all give the following:

`▬▬ Pushing Languages ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/Users/giusycammarano/.rvm/gems/ruby-2.4.2/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:133:in `block in push_exclude_paths': undefined method `match?' for "wp-content":String (NoMethodError)
Did you mean?  match
        from /Applications/MAMP/Library/lib/ruby/2.3.0/pathname.rb:327:in `ascend'
        from /Users/giusycammarano/.rvm/gems/ruby-2.4.2/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:131:in `each_with_object'
        from /Users/giusycammarano/.rvm/gems/ruby-2.4.2/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:131:in `push_exclude_paths'`

-w -d  seem to work fine.

Running MAMP, and connecting with ssh.

We've explored just about every option online - can you please suggest a solution.

Many thanks,

**Comment by pioneerskies** [comment]
I cannot get what's exactly happening in you environment, but the problem seems to be that you're calling mixed ruby versions:

* 2.4.2 (which is ok) from RVM
* 2.3.0 from /Applications/MAMP/Library/lib/ruby/ (which is unsupported by Wordmove)

I really have no idea why a ruby version is inside MAMP and in your `$PATH` and why calls to mixed interpreters happen. You should be able to unload `/Applications/MAMP/Library/lib/ruby/` from your path and that should do the trick; but I have no idea at all about how MAMP works.

**Comment by pioneerskies** [comment]
Stalled thus closing
