### ISSUE TITLE
Error on mysqldump Windows

### ISSUE THREAD

**Issue by cvbrian** [welaika/wordmove#539]
I'm running Wordmove on Windows 10 WSL. I have got it to work but for some reason the last few times I get this error `mysqldump: Got error: 1698: "Access denied for user 'root'@'localhost'" when trying to connect` for the command `mysqldump --host=127.0.0.1 --user=root --password=root --result-file="/mnt/d/Laragon/www/wp-csc/wp-content/dump.sql" wp-csc`
I am using Laragon on my computer for the website. 
I've tried updating my root user password to root on wsl and Laragon and that doesn't seem to help. 
Can anyone point me in the right direction with this?

**Comment by pioneerskies** [comment]
Hi,

if you tried to launch the command `mysqldump --host=127.0.0.1 --user=root --password=root --result-file="/mnt/d/Laragon/www/wp-csc/wp-content/dump.sql" wp-csc` directly in your shell and it's not working, than it can't be a Wordmove issue :(

`mysqldump` is a mysql built-in command just used by Wordmove. You must make it work standalone before retrying w/ Wordmove.

Since that error is an authentication/authorization problem, my advice is to update `host` `user` and `password` just as configured in your `wp-config.php` (if you already have one).

**Comment by pioneerskies** [comment]
Stalled
