### ISSUE TITLE
Push/pull between two sites on localhost

### ISSUE THREAD

**Issue by tomathyg** [welaika/wordmove#553]
My host has an unconfigurable push/pull system between staging and live sites on the same server.

What's the best way to achieve this using Wordmove?

I am unable to install sshpass and I can't get a keyless 'ssh localhost' connection working.

**Comment by pioneerskies** [comment]
I'm really sorry @tomathyg , but I can't figure out your scenario.

Would you mind to better describe all of your environments and your final goal? «achieve this» is way too cryptic from here 😄 

TIA

**Comment by tomathyg** [comment]
Sorry, I tried my best to be clear! :)

I'm just trying to push/pull between two sites that are both on localhost.

The obvious way seems to be to just ssh to localhost, so that Wordmove doesn't know any different. However, I can't get a localhost to localhost shh connection going with a key pair, although some people have managed it - do you have any ideas regarding this?

I'm not allowed to install sshpass and just put the password in the movefile.

I think my only other option would be to modify Wordmove - unless there's a way to have two local environments in the movefile?

My end goal is to push/pull from within Wordpress, triggering Wordmove in the background.

**Comment by pioneerskies** [comment]
Oh now I see...thanks for your patience.

Unfortunately I have to say that Wordmove is not built to work locally, but only between different hosts; so there is no way to have 2 local environments.

I have no knowledge about the network setup you'd need to "cheat" and use the localhost as an SSH server for connections coming from localhost.

Honestly I think that for your needs this tool could be more a pain than a utility. Why not just write a script wrapping a couple of `rsync` and `wp-cli` commands?

I fear I will close this issue because is out of the scope of Wordmove's functionality :( Obviously feel free to reopen and/or use it to continue the conversation if you need to.

I wish you best luck.

**Comment by tomathyg** [comment]
I’ve managed to solve this.

I was simply adding the public ssh key in the wrong way. With my host (Cloudways), you have to add it in the control panel rather than directly to ~/.ssh/authorized_keys.

Basically, you should always be able to ssh localhost/127.0.0.1, which means you can easily use Wordmove for two local environments.

**Comment by pioneerskies** [comment]
Interesting trick there!

Hooray

**Comment by tomathyg** [comment]
It works fine :)

Hope that's helpful to someone else!
