### ISSUE TITLE
how to allow wpcli to run as root inside a docker container?

### ISSUE THREAD

**Issue by bongoman** [welaika/wordmove#607]
wp cli is aborting the pull -d wordmove command due to it's inability to run as root.

Is there a way to flag the wpcli db commands with the "--allow-root" option ?

**Comment by pioneerskies** [comment]
Hmmm...as you can see in this test https://github.com/welaika/wordmove/blob/ba959f0a5fb3e0c81026a16a7bad885172fb37a1/spec/sql_adapter/wpcli_spec.rb wordmove is already calling `wp` passing `--allow-root`. And I think it was implemented mainly in order to support docker out-of-the-box.

Here the commit https://github.com/welaika/wordmove/commit/212221853bd2d5e18997e1dcd583fdc57f7a1ac6

Any chance you're running an old wordmove version?
