### ISSUE TITLE
doctor errors 

### ISSUE THREAD

**Issue by stevencapuzzi** [welaika/wordmove#612]
Hi, im trying to pull (wordmove pull -e production -du) but i get errors, when i run the doctor I get:

▬▬ Validating movefile section: local ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

    ❌  error | [/exclude] key 'exclude:' is undefined.

▬ Validating movefile section: production ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

    ❌  error | [/ssh/port] 'xxxxx': not a integer.

 ❌  error |   We can't connect to the MySQL server using credentials
                specified in the Movefile. Double check them or try
                to debug your system configuration.

                The command used to test was:

                mysql --host=vvv.test --user=external --password=external -e'QUIT'

    ❌  error |   We can't connect to the database using credentials
                specified in the Movefile, or the database does not
                exists. Double check them or try to debug your
                system configuration.

                The command used to test was:

                mysql --host=vvv.test --user=external --password=external ah_development -e'QUIT'

**Environment:**
- OS: Big Sur version 11.0.1
- Ruby: 2.6.3p62
- Wordmove: 5.2.1

**Comment by pioneerskies** [comment]
Hi @stevencapuzzi ,

> error | [/exclude] key 'exclude:' is undefined.

`exclude` key is actually unexpected under `local`. This is not blocking since it will simply be ignored.

> error | [/ssh/port] 'xxxxx': not a integer.

just use an iteger to setup the ssh port and this will be solved.

The last error is the real problem, but I can't say where the problem actually resides. The command used to test the connection is reported. If that command is not working also wordmove will fail to connect to your db. What is your expectation? Why do you consider this scenario to be a bug in wordmove? What else command would you use to connect to your own database?

**Comment by pioneerskies** [comment]
Forgot to ask: if you launch

    mysql --host=vvv.test --user=external --password=external ah_development -e'QUIT'

in your console what's the actual mysql's error? This is the real thing you should get.

**Comment by pioneerskies** [comment]
Closing since staled.
