### ISSUE TITLE
Invalid byte sequence in UTF-8 on db synchronize

### ISSUE THREAD

**Issue by lucdecri** [welaika/wordmove#74]
Hi, 
i have take old wordpress site, and i want sync it on my localhost.

Files are correctly synchronized, but when push (or pull) db, terminal write 
"adapt dump
/Users/luca/.rvm/gems/ruby-2.0.0-p247/gems/wordmove-1.1.0/lib/wordmove/sql_adapter.rb:44:in `gsub!': invalid byte sequence in UTF-8 (ArgumentError)"
and view a lot of error.

with other site from this remote server and on this localhost, wordmove work properly

 an you help me?

**Comment by anhdq1801** [comment]
i found this solution and solve my issue:
back to your root folder of vagrant.
use   `vagrant ssh`
1) Modified/created a '.profile'
`nano ~/.profile`

2) added these two lines to .profile:
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by rustyblue100** [comment]
Tried all of the above and still have this error, somedody has an idea? Thank you .

` /usr/local/rvm/gems/ruby-2.3.3/gems/wordmove-2.0.0/lib/wordmove/sql_adapter.rb:44:in  'gsub!': invalid byte sequence in UTF-8 (ArgumentError)`

**Comment by rustyblue100** [comment]
Fixed it by removing the Wordfence plugin and delete all the content of the tables starting with a "wf" prefix

**Comment by udolino** [comment]
if you don't want to uninstall the Wordfence plugin, but don't need to wordmove the Wordfence config / database tables, try adding this to the Movefile (nested under environment -> database):

`mysqldump_options: "--ignore-table=DATABASENAME.wp_wfVulnScanners --ignore-table=DATABASENAME.wp_wfThrottleLog --ignore-table=DATABASENAME.wp_wfStatus --ignore-table=DATABASENAME.wp_wfSNIPCache --ignore-table=DATABASENAME.wp_wfScanners --ignore-table=DATABASENAME.wp_wfReverseCache --ignore-table=DATABASENAME.wp_wfNet404s --ignore-table=DATABASENAME.wp_wfLogins --ignore-table=DATABASENAME.wp_wfLocs --ignore-table=DATABASENAME.wp_wfLockedOut --ignore-table=DATABASENAME.wp_wfLeechers --ignore-table=DATABASENAME.wp_wfKnownFileList --ignore-table=DATABASENAME.wp_wfIssues --ignore-table=DATABASENAME.wp_wfHoover --ignore-table=DATABASENAME.wp_wfHits --ignore-table=DATABASENAME.wp_wfFileMods --ignore-table=DATABASENAME.wp_wfCrawlers --ignore-table=DATABASENAME.wp_wfConfig --ignore-table=DATABASENAME.wp_wfBlocksAdv --ignore-table=DATABASENAME.wp_wfBlocks --ignore-table=DATABASENAME.wp_wfBlockedIPLog --ignore-table=DATABASENAME.wp_wfBadLeechers"`

It's not pretty, and might break if Worfence adds new tables, but it works for now. Hopefully Wordfence will fix their tables, I told them about this issue here: https://wordpress.org/support/topic/different-collations-after-installation/#post-8742910

**Comment by eivindml** [comment]
@udolino Thanks! This worked best for me. And I usually don't need wordfence when pulling production -> local.

But how will this be when pushing back from local to production? Will these tables be removed, or will they be untouched?

This is another wordfence table i found: `--ignore-table=DATABSAENAME.wf_wfNotifications`

**Comment by pioneerskies** [comment]
@eivindml you have to put exclusions in both local and production sections :)

**Comment by eivindml** [comment]
Annoying issue. Would be great if more people could ask for a reply over at [Wordfence support](https://wordpress.org/support/topic/different-collations-after-installation/#post-9077347).

I'm having issues with this on most projects. There's always some new Wordfence table or something on new projects.

**Comment by jwktje** [comment]
Also having this issue

**Comment by pioneerskies** [comment]
@jwktje these problems should be avoided using the new `sql_adapter: 'wpcli'` option, in my opinion. Despite I think it's a little fault to mix different collations in a db, `wpcli` should manage to solve this scenario.

Please, give it a try.

**Comment by eivindml** [comment]
@pioneerskies Just tried it on one of my projects always giving me this issue, and unfortunately it didn't work. Same errors.

Should the `wpcli` adapter be able to work with FTP as well, or does it have to be over SSH? 

I know it's not a good idea with different collations in a db, but my problem is that the Wordfence plugin does this, and it seems like the have no plans to fix it. And one of my clients love's this plugin and adds it to all sites, which again gives me this problem for nearly all my projects. 😭

**Comment by ydnikolaev** [comment]
lost a day fighting with this

tried everything from this [wiki page](https://github.com/welaika/wordmove/wiki/invalid-byte-sequence-in-UTF-8-while-pushing---pulling-db) without any success

adding 

`mysqldump_options: "--hex-blob --default-character-set=utf8"`

solve the problem for me

I'v also set sql_adapter to default
